### PR TITLE
Prevent nagging SMS and updated Twilio send method

### PR DESCRIPTION
**Pull request by jsammarco**
Twilio would not send using the latest npm install. Default is 3 hour
delay between SMS sends to prevent nagging.

### CODE REVIEW

**Comment by ezekg** [comment]
Looks good. Is the 3h delay between messages something that is enforced by Twilio now? If not, we should add a flag so the delay is customizable (maybe `--sms-timeout`). Reason being is that it's very well possible that you could miss a deal with a delay that long. Just today I saw a flight drop $50 for ~30m and then revert back. Also, you need to update the README with this info as well.

**Comment by jsammarco** [comment]
Thanks, No Twilio is not enforcing it. I just got bugged today every 15min there was a deal. Good idea with the timeout but ya it should only sms again in 3 hours with my tweak but we should have it do the delay only if the price was unchanged. I don’t have time to work on my branch again tonight but will do another pull request when I do.

Joe

**Comment by ezekg** [comment]
Cool. That sounds good. 👌

**Comment by ezekg** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
