### PR TITLE
Add capability to watch specific flight numbers

### LINKED ISSUE #2: Monitor specific flight?
One of the great things about Southwest is that if you already have a flight and the fare drops (regardless of if you used money or points), you can change the flight and get a refund of the difference.  That is what I really want to use this project for.  Therefore, it would be great if there was an option to monitor only a specific flight -- not ALL of the flights for that day.  Maybe with a command-line option to specify either a departure time or a departure flight number?

Thanks!

### PR DESCRIPTION
**Pull request by hoverduck**
This adds the ability to watch specific flights for price drops.

@ezekg - In order to pull the flight numbers and correlate them to the prices I had to change the way it's scraping the page.  I'm not super familiar with osmosis, so there may be a better way to do it, but this seems to work.  I'm just pulling all of the necessary info off of a convenient `hidden` input element.

Closes #2

### CODE REVIEW

**Comment by ezekg** [comment]
Hey, could you rebase the relevant commits onto master? You're including commits from your previous PR, so it's tough to review this single feature. Also, be sure to match the existing code style as best as possible as I noticed a few semi-colons and spaces around parenthises. 🙂

**Comment by jgoggan** [comment]
It looks like one-way is broken in this version, yes?  I think this happened and was fixed back in the main, but not here maybe?

In any case, really looking forward to having this completed and merged back into main!  Great feature!

**Comment by hoverduck** [comment]
Sorry, I've been busy the last couple weeks and haven't had a chance to rebase and clean this up.  I'll get to it sometime this week 😕

**Comment by jgoggan** [comment]
Sounds good!  I poked around some more and I do think the --one-way option is broken in your branch.  If I have more time to look into why, I'll let you know.  Thanks!

**Comment by ezekg** [comment]
@jgoggan I broke the `--one-way` flag in master (oops) but it's since been fixed. Should be good after @hoverduck has a chance to rebase.

**Comment by jgoggan** [comment]
I did notice that, but the change is more complex than your fix, I think.  It looks like that entire section has been re-written?  In any case, it isn't just a "change OR to AND" thing like yours needed in master.  (Again, I just took a quick look, but that was my impression.)

**Comment by hoverduck** [comment]
Closing in favor of #51

**Pull request closed without merging**
