### PR TITLE
Added support for Telegram messaging

### PR DESCRIPTION
**Pull request by hoverduck**
I've added support for sending a message via a Telegram bot, along with instructions on how to set that up.  Let me know if I need to tweak anything.

Thanks!

### CODE REVIEW

**Comment by ezekg** [comment]
Awesome stuff. It looks like Telegram messaging [should also be added here](https://github.com/hoverduck/swa-dashboard/blob/10b735f34ed129d966a1a42443b186a8fd7c6ee2/index.js#L606-L613). It may be easier to abstract the message sending into a `sendMessage` function that would then send using the services are currently enabled. Not required, but that would at least cut down on duplication and make sure that nothing is overlooked like the above section. 👍

**Comment by hoverduck** [comment]
Ah, yep...totally missed that.  I agree that abstracting it out makes sense.  I'll take care of that tomorrow morning and send it back your way.  Thanks

**Comment by hoverduck** [comment]
@ezekg Updated, care to take a look?

**Comment by ezekg** [comment]
Looks great. 👌

**Pull request merged**
